@TM:1355095364
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1355095373
@N: FP130 :"":0:0:0:-1|Promoting Net CoreUARTapb_0.CUARTOOlI.genblk9\.genblk10\.CUARTlOOI.CUARTlOlI.CUARTOO0I[0] on CLKINT  I_80 
@N: FP130 :"":0:0:0:-1|Promoting Net CoreUARTapb_0.CUARTOOlI.genblk7\.genblk8\.CUARTO11.CUARTlOlI.CUARTOO0I[0] on CLKINT  I_81 
@N: MF176 :"":0:0:0:-1|Default generator successful 
@N: MF176 :"":0:0:0:-1|Default generator successful 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MF322 :"":0:0:0:-1|Retiming summary: 0 registers retimed to 6 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock final_mss|MSS_ADLIB_INST_EMCCLK_inferred_clock with period 1000.00ns. A user-defined clock should be declared on object "n:final_mss_0.MSS_ADLIB_INST_EMCCLK"
@W: MT420 :"":0:0:0:-1|Found inferred clock final_mss_tmp_MSS_CCC_0_MSS_CCC|final_mss_0_FAB_CLK_0_inferred_clock with period 1000.00ns. A user-defined clock should be declared on object "n:final_mss_0_FAB_CLK_0"
@W: MT420 :"":0:0:0:-1|Found inferred clock final_mss_tmp_MSS_CCC_0_MSS_CCC|MSS_ADLIB_INST_FCLK_inferred_clock with period 1000.00ns. A user-defined clock should be declared on object "n:final_mss_0.MSS_ADLIB_INST_FCLK"
@TM:1355095364
@N: CG364 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\smartfusion.v":1133:7:1133:9|Synthesizing module GND
@N: CG364 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\smartfusion.v":1814:7:1814:9|Synthesizing module VCC
@N: CG364 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\smartfusion.v":2566:7:2566:11|Synthesizing module RCOSC
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":13:0:13:7|Synthesizing module CoreAPB3
@W: CG775 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":13:0:13:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":208:0:208:6|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":210:0:210:3|M
@W: CL246 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":217:0:217:4|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":356:0:356:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":363:0:363:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":370:0:370:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":377:0:377:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":384:0:384:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":391:0:391:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":398:0:398:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":405:0:405:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":412:0:412:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":419:0:419:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":426:0:426:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":433:0:433:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":440:0:440:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":447:0:447:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":454:0:454:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":458:0:458:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":460:0:460:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":462:0:462:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":464:0:464:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":466:0:466:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":468:0:468:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":470:0:470:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":472:0:472:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":474:0:474:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":476:0:476:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":478:0:478:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":480:0:480:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":482:0:482:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":484:0:484:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":486:0:486:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":490:0:490:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":492:0:492:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":494:0:494:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":496:0:496:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":498:0:498:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":500:0:500:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":502:0:502:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":504:0:504:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":506:0:506:8|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":508:0:508:9|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":510:0:510:9|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":512:0:512:9|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":514:0:514:9|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":516:0:516:9|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3.v":518:0:518:9|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\DirectCore\CoreAPB3\3.0.103\rtl\vlog\core_obfuscated\coreapb3_muxptob3.v":13:0:13:5|Synthesizing module CAPB3O
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":23:7:23:15|Synthesizing module INBUF_MSS
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":37:7:37:16|Synthesizing module OUTBUF_MSS
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":67:7:67:15|Synthesizing module BIBUF_MSS
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":151:7:151:13|Synthesizing module MSS_CCC
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\final_mss.v":5:7:5:15|Synthesizing module final_mss
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":5:7:5:37|Synthesizing module final_mss_tmp_MSS_CCC_0_MSS_CCC
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":36:7:36:10|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":37:7:37:14|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":38:7:38:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":39:7:39:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":40:7:40:10|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":41:7:41:14|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":42:7:42:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":43:7:43:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":44:7:44:10|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":45:7:45:14|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":46:7:46:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":47:7:47:15|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":48:7:48:13|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":49:7:49:11|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":50:7:50:13|M
@W: CL157 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":62:7:62:18|M
@TM:1355095373
@W: MO111 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_mss\mss_ccc_0\final_mss_tmp_mss_ccc_0_mss_ccc.v":62:7:62:18|M
@TM:1355095364
@W: CL157 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":63:7:63:20|M
@TM:1355095373
@W: MO111 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_mss\mss_ccc_0\final_mss_tmp_mss_ccc_0_mss_ccc.v":63:7:63:20|M
@TM:1355095364
@W: CL157 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\MSS_CCC_0\final_mss_tmp_MSS_CCC_0_MSS_CCC.v":64:7:64:18|M
@TM:1355095373
@W: MO111 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_mss\mss_ccc_0\final_mss_tmp_mss_ccc_0_mss_ccc.v":64:7:64:18|M
@W:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_mss\mss_ccc_0\final_mss_tmp_mss_ccc_0_mss_ccc.v":81:40:81:47|M
@W:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_mss\mss_ccc_0\final_mss_tmp_mss_ccc_0_mss_ccc.v":81:40:81:47|M
@TM:1355095364
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_mss\mss_tshell.v":1:7:1:13|Synthesizing module MSS_APB
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Clock_gen.v":30:0:30:32|Synthesizing module final_top_CoreUARTapb_0_Clock_gen
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Clock_gen.v":70:0:70:16|M
@TM:1355095373
@N:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\clock_gen.v":962:0:962:5|M
@N:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\clock_gen.v":1039:0:1039:5|M
@TM:1355095364
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUART.v":14:0:14:31|Synthesizing module final_top_CoreUARTapb_0_COREUART
@W: CG133 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUART.v":320:0:320:7|M
@TM:1355095373
@W: BN132 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\coreuart.v":851:0:851:5|M
@TM:1355095364
@N: CL201 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUART.v":895:0:895:5|M
@W: CL169 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUART.v":1062:0:1062:5|M
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUART.v":1209:0:1209:7|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":14:0:14:34|Synthesizing module final_top_CoreUARTapb_0_CoreUARTapb
@W: CL246 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":113:0:113:4|M
@W: CG133 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":270:0:270:8|M
@A: CL153 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":270:0:270:8|M
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":700:0:700:8|M
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\CoreUARTapb.v":776:0:776:8|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":14:0:14:33|Synthesizing module final_top_CoreUARTapb_0_fifo_256x8
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":44:0:44:7|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":151:0:151:36|Synthesizing module final_top_CoreUARTapb_0_fifo_ctrl_256
@A:  :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":541:0:541:5|M
@TM:1355095373
@N: BN116 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":541:0:541:5|M
@N: BN116 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":541:0:541:5|M
@TM:1355095364
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":588:0:588:8|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":634:0:634:30|Synthesizing module final_top_CoreUARTapb_0_ram16x8
@TM:1355095373
@N: BN116 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":768:0:768:5|M
@N: BN116 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":768:0:768:5|M
@TM:1355095364
@N: CL134 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":768:0:768:5|M
@TM:1355095373
@N: MF135 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":768:0:768:5|M
@N: MF135 :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\fifo_256x8.v":768:0:768:5|M
@TM:1355095364
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":14:0:14:31|Synthesizing module final_top_CoreUARTapb_0_Rx_async
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":81:0:81:7|M
@TM:1355095373
@N:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\rx_async.v":422:0:422:5|M
@TM:1355095364
@W: CL169 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":503:0:503:5|M
@W: CL190 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":503:0:503:5|M
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":654:0:654:7|M
@W: CL169 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":723:0:723:5|M
@W: CL190 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":723:0:723:5|M
@N: CL201 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":723:0:723:5|M
@TM:1355095373
@N:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\rx_async.v":967:0:967:5|M
@TM:1355095364
@W: CL169 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":1414:0:1414:5|M
@N: CL177 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":1414:0:1414:5|M
@W: CL190 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Rx_async.v":1414:0:1414:5|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Tx_async.v":14:0:14:31|Synthesizing module final_top_CoreUARTapb_0_Tx_async
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Tx_async.v":60:0:60:7|M
@W: CL159 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Tx_async.v":68:0:68:7|M
@N: CL201 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Tx_async.v":253:0:253:5|M
@TM:1355095373
@N:  :"c:\users\thinkpad\documents\github\eecs373final\controller_screen\hw\component\work\final_top\coreuartapb_0\rtl\vlog\core_obfuscated\tx_async.v":550:0:550:5|M
@TM:1355095364
@N: CG179 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\CoreUARTapb_0\rtl\vlog\core_obfuscated\Tx_async.v":794:0:794:8|M
@N: CG364 :"C:\Users\thinkpad\Documents\GitHub\eecs373final\controller_screen\HW\component\work\final_top\final_top.v":5:7:5:15|Synthesizing module final_top
